### ISSUE TITLE
Allow yaml merging feature

### ISSUE THREAD

**Issue by rlindner81** [SAP/cloud-mta#118]
I would like to use the yaml merging feature in my mta files for clarity
https://yaml.org/type/merge.html

See
https://github.wdf.sap.corp/S4HANAFIN/AFC/blob/_better_mta_yaml/mta.yaml

MTA (deployment) colleagues say this is ok for them in the deployment descriptor however the builder, so far is not dealing will with it.

```
[2019-11-21 17:04:40]  INFO generating the "Makefile_20191121170440.mta" file...
[2019-11-21 17:04:40]  INFO done
[2019-11-21 17:04:40]  INFO executing the "make -f Makefile_20191121170440.mta p=cf mtar=afc.mtar strict=true mode=" command...
[2019-11-21 17:04:40]  INFO validating the MTA project
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x132d7eb]

goroutine 1 [running]:
github.com/SAP/cloud-mta/validations.checkDeprecatedOpt(0xc000254ae0, 0xc0003385a0, 0x1617f85, 0x8, 0x0, 0x0, 0x0)
        /Users/i056926/go/pkg/mod/github.com/!s!a!p/cloud-mta@v0.0.6-0.20191103113612-54d2eb3314b3/validations/semantic_deprecated_opts.go:19 +0x16b
github.com/SAP/cloud-mta/validations.checkDeprecatedOpts(0xc00019fa00, 0xc000382be0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/i056926/go/pkg/mod/github.com/!s!a!p/cloud-mta@v0.0.6-0.20191103113612-54d2eb3314b3/validations/semantic_deprecated_opts.go:36 +0x1da
github.com/SAP/cloud-mta/validations.runSemanticValidations(0xc00019fa00, 0xc000382be0, 0x0, 0x0, 0x7ffeefbfbebd, 0x5, 0x1, 0x0, 0x0, 0x1f72b18, ...)
        /Users/i056926/go/pkg/mod/github.com/!s!a!p/cloud-mta@v0.0.6-0.20191103113612-54d2eb3314b3/validations/semantic_validate.go:76 +0x1ad
github.com/SAP/cloud-mta/validations.validate(0xc000232000, 0x3a87, 0x4000, 0x0, 0x0, 0x10101, 0x7ffeefbfbebd, 0x5, 0x3a87, 0x0, ...)
        /Users/i056926/go/pkg/mod/github.com/!s!a!p/cloud-mta@v0.0.6-0.20191103113612-54d2eb3314b3/validations/mta_validate.go:114 +0x230
github.com/SAP/cloud-mta/validations.MtaYaml(0x0, 0x0, 0x1617f65, 0x8, 0x10101, 0x7ffeefbfbebd, 0x5, 0x0, 0x0, 0x163dc18, ...)
        /Users/i056926/go/pkg/mod/github.com/!s!a!p/cloud-mta@v0.0.6-0.20191103113612-54d2eb3314b3/validations/mta_validate.go:48 +0x208
github.com/SAP/cloud-mta-build-tool/internal/artifacts.ExecuteValidation(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffeefbfbeb5, ...)
        /Users/i056926/go/src/github.com/SAP/cloud-mta-build-tool/internal/artifacts/validate.go:34 +0x241
github.com/SAP/cloud-mta-build-tool/cmd.glob..func3(0x1aa0ee0, 0xc0000d7420, 0x0, 0x2, 0x0, 0x0)
        /Users/i056926/go/src/github.com/SAP/cloud-mta-build-tool/cmd/cmd.go:131 +0xdb
github.com/spf13/cobra.(*Command).execute(0x1aa0ee0, 0xc0000d7400, 0x2, 0x2, 0x1aa0ee0, 0xc0000d7400)
        /Users/i056926/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x1aa00a0, 0x0, 0xa6000, 0xc0000a4058)
        /Users/i056926/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/i056926/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/SAP/cloud-mta-build-tool/cmd.Execute(...)
        /Users/i056926/go/src/github.com/SAP/cloud-mta-build-tool/cmd/root.go:33
main.main()
        /Users/i056926/go/src/github.com/SAP/cloud-mta-build-tool/main.go:11 +0x2e
make: *** [pre_validate] Error 2
Error: could not build the MTA project: could not execute the "make -f Makefile_20191121170440.mta p=cf mtar=afc.mtar strict=true mode=" command: exit status 2
```

**Comment by katunin-ng** [comment]
Hi @rlindner81 

Supporting this feature is currently not planned.
Please elaborate in what use case you would like to apply this feature.
We may re-consider the priority depending on how common the use case is.

Regards
Natalia

**Comment by rlindner81** [comment]
Did you have a look at the example I provided? I would like to apply this feature to every MTA file I run (I wrote two bigger builds with MTA so far). I find it obvious that avoiding redundancy helps to minimize errors.

The current yaml files that describe the MTA build often have loads of parameters that are the same across modules, that is where the merge is so powerful because you can define your own defaults and get a better overview and ultimately a shorter description that is more on point.

**Comment by allaVolkov** [comment]
Hi Richard,

Please check this with release 1.0.7 of cloud-mta-build-tool.  It must be fixed.

Thank you and regards,
Alla

**Comment by rlindner81** [comment]
@katunin-ng FYI https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#minimize-duplication

@allaVolkov I cannot check it right now, but reading the release logs, I doubt 1.0.7 is any different than the version I tried previously. I would expect some kind of reference to YAML anchors.

**Comment by allaVolkov** [comment]
@rlindner81 I run validation on your mta.yaml file with master version and it finished without nil pointer exception. I expect that this change https://github.com/SAP/cloud-mta/pull/119/files fixes it.

**Comment by rlindner81** [comment]
Right, that sounds good! I will do a check on Tuesday then :)

**Comment by rlindner81** [comment]
I ran a test and it works for me now. Thanks, I will close this issue.
